#multi-stage
#1) build with node 16
#2) serve with nginx
#builder
FROM node:16.20.2 AS builder
WORKDIR /app

# Bundle app sources
COPY package.json yarn.lock ./

RUN yarn install

COPY . /app

EXPOSE 8080

CMD yarn serve --port 8080
#ENTRYPOINT ["nginx", "-g", "daemon off;"]