version: '3.10'

#----------------------
#----------------------
services:

  frontend:
  #----------------------     
    build: ./frontend

    command: nginx -g "daemon off;"
    
    ports:
    - 80:80
    
    depends_on:
      backend:
        condition: service_healthy

  backend: 
  #----------------------
    build:  
      context: ./backend
      dockerfile: Dockerfile.prod

    command: uvicorn rimsdash.main:app --host 0.0.0.0 --port 5000

    ports:
    - 5000:5000

    healthcheck:
      test: curl --fail http://localhost:5000/rapi/v1/ready || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s      

    depends_on:
      db:
        condition: service_healthy

  db:
  #----------------------
    image: postgres:12

    volumes:
      - .rdb_postgres_data:/var/lib/postgresql/data/
    
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_DB_FILE=/run/secrets/db_name
    secrets:
      - db_user
      - db_name
      - db_root_password

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
        #note: attempts to connect as root and throws error in log, seems to still work
      interval: 10s
      timeout: 5s
      retries: 5

#----------------------
#----------------------
secrets:
  db_user: 
    file: .secrets/db_user.txt
  db_name: 
    file: .secrets/db_name.txt
  db_root_password: 
    file: .secrets/db_root_password.txt    

#----------------------
#----------------------
volumes:
  rdb_postgres_data_prod:
    driver: local

#----------------------
#----------------------