version: '3.10'

#----------------------
#----------------------
services:

  frontend:
  #----------------------     
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev

    volumes:
    - './frontend:/app'
    - '/app/node_modules'
    #name modules as a separate volume to avoid overwrite from local

    command: yarn serve --port 8080
    
    ports:
    - 127.0.0.1:8080:8080
    
    environment:
    - CHOKIDAR_USEPOLLING=true

    depends_on:
      backend:
        condition: service_healthy

  backend: 
  #----------------------
    build:  
      context: ./backend
      dockerfile: Dockerfile.dev

    ports:
    #app backend
    - 127.0.0.1:80:80
    #debugpy
    - 127.0.0.1:5678:5678    
    #jupyternotes
    - 127.0.0.1:8888:8888    

    volumes:
    - './backend:/app'

    command: ["sh", "-c", "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 & uvicorn rimsdash.main:app --reload --host 0.0.0.0 --port 80"]
    #uvicorn rimsdash.main:app --reload --host 0.0.0.0 --port 80

    healthcheck:
      test: curl --fail http://localhost:80/rims/api/v1/ready || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s      

    depends_on:
      db:
        condition: service_healthy

  db:
  #----------------------
    image: postgres:12

    volumes:
      - .rdb_postgres_data_dev:/var/lib/postgresql/data/
    
    ports:
    - 127.0.0.1:5432:5432

    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_DB_FILE=/run/secrets/db_name
    secrets:
      - db_user
      - db_name
      - db_root_password

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
        #note: attempts to connect as root and throws error in log, seems to still work
      interval: 10s
      timeout: 5s
      retries: 5

#----------------------
#----------------------
secrets:
  db_user: 
    file: .secrets/db_user.txt
  db_name: 
    file: .secrets/db_name.txt
  db_root_password: 
    file: .secrets/db_root_password.txt    

#----------------------
#----------------------
volumes:
  rdb_postgres_data_dev:
    driver: local

#----------------------
#----------------------