version: '3.10'

services:
  frontend: 
    build:  ./frontend
    command: python manage.py run -h 0.0.0.0
          #rimsdash-debug
    volumes:
      - ./frontend/:/app/         
    ports:
      - 8050:8050
    env_file:
      - ./.env.dev
    depends_on:
      - backend

  backend: 
    build:  ./backend
    command: python manage.py run -h 0.0.0.0
          #rimsdash-debug
    volumes:
      - ./backend/:/app/         
    ports:
      - 8050:8050
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - .postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_DB=rimsdash_db_dev

secrets:
  db_user: 
    file: .secrets/db_user.txt
  db_root_password: 
    file: .secrets/db_root_password.txt

volumes:
  .postgres_data:


    #command: gunicorn --bind 0.0.0.0:8050 rimsdash.dashboard.wsgi:server    