version: '3.10'

services:
  web: 
    build:  ./rimsdash
    command: gunicorn --bind 0.0.0.0:8050 frontend.wsgi:server
    expose:
    - 8050
  
  db:
    image: postgres:13
    volumes:
      - .postgres_data:/var/lib/postgresql/data/


  nginx:
    build: ./nginx
    ports:
    - 80:80
    depends_on:
    - web