version: '3.10'

services:
  web: 
    build:  ./web
    command: gunicorn --bind 0.0.0.0:8050 rimsdash.dashboard.wsgi:server
    expose:
    - 8050
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - .postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_DB=rimsdash_db_prod
  
  nginx:
    build: ./nginx
    ports:
    - 80:80
    depends_on:
    - web

secrets:
  db_user: 
    file: .secrets/db_user.txt
  db_root_password: 
    file: .secrets/db_root_password.txt


volumes:
  .postgres_data_prod: