FROM python:3.10.6
WORKDIR /app

#set up the container
RUN apt-get update && apt-get -y install \
    vim \    
    gcc

RUN pip install --upgrade pip

#compose binds backend/ to /app/ as volume
#can install directly without copying
COPY ./setup.cfg /app
COPY ./pyproject.toml /app

ENV PYTHONPATH "${PYTHONPATH}:/app"

#RUN pip install debugpy

#debugpy port
#EXPOSE 5678

RUN pip install -e /app[dev]

COPY ./conf/rimsdash.conf /app/conf

#entrypoint
CMD uvicorn rimsdash.main:app --reload --host 0.0.0.0 --port 80