FROM python:3.10.6
WORKDIR /app

#set up the container
RUN apt-get update && apt-get -y install \
    vim \    
    gcc

RUN pip install --upgrade pip

#copy and install
COPY . /app
RUN pip install /app

#entrypoint
CMD uvicorn rimsdash.main:app --host 0.0.0.0 --port 5000