---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-rimsdash-db
  namespace: clowder2
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi